apiVersion: v1
kind: ConfigMap
metadata:
  name: python-app-config
  namespace: db
data:
  main.py: |
    import os
    import psycopg2
    psycopg2.connect(
        host="postgres.db.svc.cluster.local",
        port=5431,
        database="appdb",
        user=os.getenv("POSTGRES_USER"),
        password=os.getenv("POSTGRES_PASSWORD")
    )

