apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: db
spec:
  selector:
    app: python-app   # must match Deployment labels
  ports:
    - protocol: TCP
      port: 5000        # Service port (inside cluster)
      targetPort: 5000  # Container port (Flask app)
      nodePort: 30080   # External port (optional, can be auto-assigned)
  type: NodePort

