apiVersion: v1
kind: Service
metadata:
  name: python-app-service
  namespace: db
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 5000        # Service port
      targetPort: 5000  # Container port
      nodePort: 30080   # External port (must be in 30000â€“32767 range)
  type: NodePort

