apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-migrate
  namespace: db
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: liquibase
          image: liquibase/liquibase:4.27.0
          volumeMounts:
            - name: changelog-volume
              mountPath: /liquibase/changelog
          env:
            - name: LIQUIBASE_URL
              value: jdbc:postgresql://postgres:5431/postgres
            - name: LIQUIBASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: LIQUIBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Postgres..."
              until pg_isready -h postgres.db.svc.cluster.local -p 5431 -U $LIQUIBASE_USERNAME; do
                echo "Postgres not ready, sleeping 5s..."
                sleep 5
              done
              echo "Postgres ready. Running Liquibase..."
              liquibase update
      volumes:
        - name: changelog-volume
          configMap:
            name: liquibase-changelog

