apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-migrate
  namespace: db
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: liquibase
          image: liquibase/liquibase:4.27.0
          volumeMounts:
            - name: changelog-volume
              mountPath: /liquibase
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          args:
            - --url=jdbc:postgresql://postgres:5431/postgres
            - --username=$(POSTGRES_USER)
            - --password=$(POSTGRES_PASSWORD)
            - --changeLogFile=/liquibase/master.xml
            - update
      volumes:
        - name: changelog-volume
          configMap:
            name: liquibase-changelog

