apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: db
spec:
  selector:
    app: postgres
  type: LoadBalancer   # or NodePort if preferred
  ports:
    - port: 5431       # external port
      targetPort: 5432 # container port
      protocol: TCP
      name: postgres

