apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce   # one pod will use it
  resources:
    requests:
      storage: 1Gi    # adjust size if needed
  storageClassName: nfs-client

