apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteMany   # NFS provisioner requires RWX
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client

