apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce   # or ReadWriteMany if multiple pods need access
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client

