apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: db-ns
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432         # Service port
      targetPort: 5432   # Container port
  type: ClusterIP        # internal access only


